const CART_REDUCER_TYPES = {
  TOGGLE_CART: "cart/TOGGLE_CART",
  CLOSE_CART: "cart/CLOSE_CART",
  CHANGING_CART_ITEMS_IN_CART: "cart/CHANGING_CART_ITEMS_IN_CART",
};

export default CART_REDUCER_TYPES;
